nombre_run: 'model_selection_titanic'

nombre_experiment: 'titanic_v1'

aliases_champion: 'champion'
nombre_usecase: 'titanic'


num_features : ["Age", "Fare", "SibSp", "Parch"]
cat_features : ["Sex", "Embarked", "Pclass"]

target : 'Survived'

path_input_data_ingesta: 'data/0_input/titanic_train.csv'
path_output_data_ingesta: 'data/raw/titanic_train.csv'

